### PR TITLE
Major Improvements

### PR DESCRIPTION
**Pull request by throny**
Hi, just made some changes:
- input of scammer URL at startup 
- generating random strings (default: 5242880 length / ~5MB)
- removed the name-list as it is not needed anymore
- adjusted output (default size of 1 request is ~10MB)

TODOs: 
- multithread so the server gets flooded with requests
- check input url for protocol and/or auth path
- maybe implement tor stuff (but that sounds overkill for now as the most are protected by cloudflare anyway)
- add possibility to spam mail instead of username (for different kind of websites)

### CODE REVIEW

**Comment by valplusplusle** [comment]
With this code you have one Problem. If code of the phishing site tests the validation of the email on server side, there will be something wrong. For the password the random one is nice but for the email we need some realistic ones with an @XYZ.DOMAIN

**Comment by throny** [comment]
Why tho? I never login with email to steam tbh. It just asks for the steam username.

**Comment by valplusplusle** [comment]
Yes but what if you want to use the tool on a page with email login?

**Comment by throny** [comment]
I thought the purpose is just spamming steam scam sites. That would be a possible improvement for the given todo list above :)

**Pull request closed without merging**
