### PR TITLE
Update makeaccount.py

### PR DESCRIPTION
**Pull request by throny**
changed lib to urllib3 and made the output more useful. (if http 503 then theres something wrong with your request!)

### CODE REVIEW

**Review by valplusplusle — APPROVED** [review]
nice!:)

**Comment by throny** [comment]
I was getting a lot of spam today so I decided to invest 5mins to improve this one as I found it on youtube as one of the first results. There are some possibilities to improve this one (e.g. getting a cloudflare cookie and enrich headers with it so even with protection it wouldn't resolve to a 503 HTTP)

**Comment by valplusplusle** [comment]
It was just a small "fun" project so feel free to edit it like you want:)

**Comment by throny** [comment]
I wonder if this is really that effective tbh. Does this cause the phisher to call the steam API? Is it possible that his IP will get blacklisted after thousands of invalid requests? If yes, I will put some effort to it :) If not, does it really appear in his control panel or is this just getting filtered out? Then it would be 100% senseless.. Maybe you know that stuff :D

**Comment by valplusplusle** [comment]
It depends on how many effort the "bad-guy" put into his fishing page. For a "bad-guy" who knows what he do, it is very easy to filter. And as mentioned there is no ip switching or something like that in the code.
BUT- usually the "bad-guys" are interested in free hosting where they dont have to put there data to the hoster. Those hosters usually have very bad conditions and a very small space. 
So when the data-space for the account information is a size like 2MB it is easy to floot this space. And when there is no more space than no one can ran into the trap.
But things to make this flooting program more usefull would be:
-adding more email variety
-adding more password variety
-add ip changing for each sending (maybe with tor functions?)
-maybe a userfriendly "interface" (would not put effort into a real ui but maybe some console ui)

**Pull request merged**
